### ISSUE TITLE
Nullsafety migration?

### ISSUE THREAD

**Issue by AlexShniperson-INO** [koa-health/mixpanel_analytics#15]
Do you have any plans to migrate to nullsafety?

**Comment by robertohuertasm** [comment]
There's a PR opened #14, we will probably review it today. Thanks for asking.

**Comment by pushpendraKh** [comment]
@robertohuertasm any update?

**Comment by robertohuertasm** [comment]
@pushpendraKh it's a busy time for us and haven't been able to find a moment to review this. Hopefully, during the week. Stay tuned.

**Comment by akshay-virohan** [comment]
hi @robertohuertasm, any update?

**Comment by robertohuertasm** [comment]
Release is coming!
